### ISSUE TITLE
개발 노선 변경에 대한 의견

### ISSUE THREAD

**Issue by Puilin** [Puilin/BS_cinema_front#2]
영화 페이지 작업 도중 발생한 이슈입니다.
메인 페이지(index.html)에서 사용했던 nav bar를 react를 이용해 컴포넌트화 하여 메인페이지에 적용하는 데 성공하였습니다. 하지만 컴포넌트 재사용을 위해 영화 페이지(moviegridfw_light.html)에서 nav bar를 적용할 방법을 찾다가 보니, React 라이브러리는 SPA(Single Page Application)에 특화된 라이브러리이기 때문에 index.html 해당 파일 하나에 대해서만 컴포넌트를 활용할 수 있다는 것을 알게 되었습니다.
 따라서 불가피하게 개발 노선을 일부 수정해야 될 필요성을 느꼈고, 이에 팀원 분들 의견을 여쭤보려 합니다.
 방향은 다음과 같이 두 가지가 있습니다.

 1. Single Page Application 포맷을 유지하면서 단일 페이지 내에서 모든 것을 구현 (React)
    - 이 경우 react로 단일 페이지를 동적으로 작성하게 됨
 2. Multiple Page Application 포맷으로 변경
  2-1. Routing을 지원하는 3rd party library인 React Router 활용 (시도해보진 않았으나 react 기능과 연계가 될 것으로 기대함. 상술한 이슈가 해결될지는 미지수)
  2-2. 기타 라이브러리 사용

**Comment by baethwjd2** [comment]
컴포넌트 재활용이 큰 장점이라 생각되고, SPA의 단점도 찾아보았는데 보안, 초기 로드 시간 문제 등의 저희와 관계 없는 product-level 문제들만 있어서 SPA 방식이 좋다고 생각됩니다.

**Comment by deukyunlee** [comment]
영화 예매 사이트의 특성 상 서버에 부하를 적게 줘서 반응성을 올리는 것이 중요하다고 생각하기 때문에, 저도 SPA 방식이 좋다고 생각합니다.

**Comment by Puilin** [comment]
더 의견 없으시면 SPA로 진행하겠습니다.
